4 feature account class creation
CSC207-2022F-UofT/course-project-justbob pull request #28
Opened 2022-11-19 22:30 UTC by AlanC12138

added text file for storing user credentials, removed gpa methods from archive and runningcourses; added more comments; modified functions in Accountlist to fit with the new textfile

2022-11-20 03:17 UTC, YuweiCai2003 submitted a review, later dismissed
Separation into different classes makes the code really efficient

2022-11-20 05:27 UTC, berrythebear reviewed
Uses of the filepath will have to be modified to work for any user. (new File(System.getProperty("user.dir"), "src\\main\\java\\accountClasses\\accountStorage") should work. Also, mkdirs() can create parts of the directory that don't yet exist such as if accountStorage is a folder. ".txt" might be needed at the end if you're using a text file to store the information

2022-11-20 05:28 UTC, berrythebear submitted a review, later dismissed

2022-11-20 23:49 UTC, MrSunshineVS requested changes
Everything looks great!!!!!! I think the test file in your branch is behind main though so try fixing that before we merge.

2022-11-20 23:49 UTC, MrSunshineVS commented on src/test/java/courseManager/CourseManagerTest.java
> +import entities.course.Course;
This file is behind main. sami's pull request was approved recently, try merging main and hopefully the issue will be resolved

2022-11-21 02:55 UTC, MrSunshineVS approved these changes

2022-11-21 02:56 UTC, closed without merging