4 feature account class creation
CSC207-2022F-UofT/course-project-justbob pull request #67
Opened 2022-12-04 20:13 UTC by AlanC12138

Implemented use cases for removing archive courses, adding semester courses, and removing semester courses. Review this plsss

2022-12-04 20:15 UTC, berrythebear submitted a review, later dismissed

2022-12-04 20:35 UTC, MrSunshineVS submitted a review, later dismissed
Good stuff! I think you forgot to save the data to the database after your usecases were finished, but other than that really nice code :)

2022-12-04 20:35 UTC, MrSunshineVS commented on src/main/java/ports/usecases/account/RemoveSemesterCourse/RemoveSemesterCourseInputBoundary.java
> +    void execute(String username, RemoveSemesterCourseRequest request) throws CourseDoesNotExistsError;
If you're using a request model, it's a good idea to encapsulate the entire input into the request model. In this case, that means moving the `username` parameter to the request model.

2022-12-04 20:35 UTC, MrSunshineVS commented on src/main/java/ports/usecases/account/addSemesterCourse/AddSemesterCourseInputBoundary.java
> +    void execute(String username, AddSemesterCourseRequest request) throws CourseAlreadyExistsError;
Similar to other usecase. `username` can be moved to the request.

2022-12-04 20:35 UTC, MrSunshineVS commented on src/main/java/ports/usecases/account/removeAchiveCourse/RemoveArchiveCourseInputBoundary.java
> +    void execute(String username, String courseCode) throws PathNotFoundError, ArchiveCourseInputBoundary.CourseNotCompletedError;
There's no reason for this method to throw a `CourseNotCompletedError`, since if a course is already in your archive it should be completed.

2022-12-04 20:35 UTC, MrSunshineVS commented on src/main/java/usecases/account/AddSemesterCourseUseCase.java
> +        account.getSemester().addCourse(course);
Make sure to save the account to the database after you're done.

2022-12-04 20:35 UTC, MrSunshineVS commented on src/main/java/ports/usecases/account/removeAchiveCourse/RemoveArchiveCourseInputBoundary.java
> +    void execute(String username, String courseCode) throws PathNotFoundError, ArchiveCourseInputBoundary.CourseNotCompletedError;
I checked over the implementation, and it doesn't throw this error. So it's safe to remove it from the declaration here.

2022-12-04 20:35 UTC, MrSunshineVS commented on src/main/java/usecases/account/RemoveArchiveCourseUseCase.java
> +        account.getArchive().removeCourse(course);
Again, you need to save the account to the database.

2022-12-04 20:35 UTC, MrSunshineVS commented on src/main/java/usecases/account/RemoveSemesterCourseUseCase.java
> +        account.getSemester().removeCourse(account.getSemester().getCourseByCode(request.courseCode));
Save account to the database.

2022-12-04 20:36 UTC, YuweiCai2003 approved these changes
good work

2022-12-04 22:02 UTC, samielsabri requested changes
looks great! the courseDoesNotExists typo is still there tho

2022-12-04 22:23 UTC, samielsabri requested changes
oh and two more things
1) add response models too so the program knows what to update
2) add limitations to input, for example in the addSemesterCourseUseCase, the courseCode should not be longer than 6 characters otherwise it will throw an error or the credit has to be either 0.5 or 1.0 otherwise it will throw an error etc.

2022-12-05 00:11 UTC, DeepSJain approved these changes
Looks good

2022-12-05 01:09 UTC, samielsabri approved these changes
looks great, thank you for implementing the changes

2022-12-05 01:11 UTC, YuweiCai2003 approved these changes
Good work

2022-12-05 01:12 UTC, vaishnav8791 approved these changes
Great Work on fixing up the edits suggested!

2022-12-05 01:19 UTC, merged