Checklist UI
CSC207-2022F-UofT/course-project-justbob pull request #92
Opened 2022-12-07 18:07 UTC by YuweiCai2003

2022-12-07 20:21 UTC, AlanC12138 submitted a review, later dismissed
good work

2022-12-07 20:35 UTC, AlanC12138 submitted a review, later dismissed

2022-12-07 20:46 UTC, samielsabri submitted a review, later dismissed
looks good

2022-12-07 20:52 UTC, DeepSJain requested changes
Lines 68 to 80 of the checklist view should be done in separate controller and presenter classes

2022-12-07 21:23 UTC, DeepSJain submitted a review, later dismissed

2022-12-07 22:25 UTC, AlanC12138 approved these changes

2022-12-07 22:29 UTC, AlanC12138 approved these changes

2022-12-07 23:34 UTC, DeepSJain approved these changes

2022-12-08 01:45 UTC, berrythebear approved these changes

2022-12-08 01:45 UTC, merged